### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by ghost** [Grocel/Anti-Noclip-Field#2]
Lua Error:
[ERROR] addons/tool_all/lua/entities/anti_noclip_field/shared.lua:69: attempt to call method 'GetShapeInt' (a nil value)
  1. UpdateShape - addons/tool_all/lua/entities/anti_noclip_field/shared.lua:69
   2. unknown - addons/tool_all/lua/entities/sent_anti_noclip_control/shared.lua:310

**Comment by Grocel** [comment]
Why did you closed it. Did the problem fix by itself after reporting?

**Comment by ghost** [comment]
it's was my mistake in the code

**Comment by ghost** [comment]
i fixed it
